name: opensuite
description: Open-source cross-platform Office & Productivity Suite.
version: 1.7.1+10
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Internal packages
  fileutility_core:
    path: ../../packages/core
  fileutility_storage:
    path: ../../packages/storage
  fileutility_ui_kit:
    path: ../../packages/ui_kit
  fileutility_l10n:
    path: ../../packages/l10n

  # State management
  flutter_bloc: ^9.1.0
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.7

  # Routing
  go_router: ^15.1.2

  # DI
  get_it: ^8.0.3

  # Utilities
  uuid: ^4.5.1
  intl: any
  collection: any
  path: any
  url_launcher: ^6.3.1

  # Storage
  sqflite: ^2.4.1
  path_provider: ^2.1.5

  # File handling
  file_picker: ^9.2.1
  share_plus: ^10.1.4
  cross_file: any
  csv: ^6.0.0
  pdfrx: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

